# Generated by Django 6.1.1 on 2026-09-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_order_orderitem_alter_cart_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=6),
        ),
    ]
